name: From Sprue To Glory integration tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_backend:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x, 22.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Run backend test and build
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./server/package-lock.json
      - run: npm ci
        working-directory: ./server
      - name: Run lint
        run: npm run lint
        working-directory: ./server
        continue-on-error: true
      - name: Lint results via reviewdog
        uses: reviewdog/action-eslint@v1
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          level: warning
          fail_on_error: false
          eslint_flags: --ext .ts src
          workdir: ./server
      - name: Run tests
        run: npm run test
        working-directory: ./server
      - name: Build the app
        run: npm run build --if-present
        working-directory: ./server

  run_frontend_test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x, 22.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Run frontend test and build
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./client/package-lock.json
      - name: Install Angular CLI
        run: npm install -g @angular/cli
        working-directory: ./client
      - run: npm ci
        working-directory: ./client
      - name: Run lint
        run: ng lint
        working-directory: ./client
        continue-on-error: true
      - name: Lint results via reviewdog
        uses: reviewdog/action-eslint@v1
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          level: warning
          fail_on_error: false
          eslint_flags: --ext .ts src
          workdir: ./client
      - name: Run tests
        run: npm run test -- --browsers=ChromeHeadless --watch=false
        working-directory: ./client
      - name: Build the app
        run: ng build
        working-directory: ./client
