name: From Sprue To Glory integration tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_backend:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Run backend test and build
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cd ./server
    - run: npm ci
    - name: Run lint 
      run: npm run lint
    - name: Run tests
      run: npm run test
    - name: Build the app
      run: npm run build --if-present

  run_frontend_test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Run frontend test and build
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cd ./client
    - run: npm ci
    - name: Run lint 
      run: ng lint
    - name: Run tests
      run: ng test
    - name: Build the app
      run: ng build --if-present
